export default {
  avatar: {
    category: 'Components',
    subtitle: '头像',
    type: 'Data Display',
    title: 'Avatar',
    tag: 'fa-avatar',
  },
  badge: {
    category: 'Components',
    subtitle: '徽标数',
    type: 'Data Display',
    title: 'Badge',
    tag: 'fa-badge',
  },
  breadcrumb: {
    category: 'Components',
    subtitle: '面包屑',
    type: 'Navigation',
    title: 'Breadcrumb',
    tag: 'fa-breadcrumb',
  },
  button: {
    category: 'Components',
    subtitle: '按钮',
    type: 'General',
    title: 'Button',
    tag: 'fa-button',
  },
  card: {
    category: 'Components',
    subtitle: '卡片',
    type: 'Data Display',
    title: 'Card',
    tag: 'fa-card',
    cols: 1,
  },
  checkbox: {
    category: 'Components',
    subtitle: '多选框',
    type: 'Data Entry',
    title: 'Checkbox',
    tag: 'fa-checkbox',
  },
  grid: {
    category: 'Components',
    subtitle: '栅格',
    type: 'Layout',
    title: 'Grid',
    tag: 'fa-row',
    cols: 1,
  },
  icon: {
    category: 'Components',
    subtitle: '图标',
    type: 'General',
    title: 'Icon',
    tag: 'fa-icon',
  },
  input: {
    category: 'Components',
    subtitle: '输入框',
    type: 'Data Entry',
    title: 'Input',
    tag: 'fa-input',
  },
  select: {
    category: 'Components',
    subtitle: '选择器',
    type: 'Data Entry',
    title: 'Select',
    tag: 'fa-select',
  },
  menu: {
    category: 'Components',
    subtitle: '导航菜单',
    type: 'Navigation',
    title: 'Menu',
    tag: 'fa-menu',
    cols: 1,
  },
  pagination: {
    category: 'Components',
    subtitle: '分页',
    type: 'Navigation',
    title: 'Pagination',
    tag: 'fa-pagination',
    cols: 1,
  },
  popconfirm: {
    category: 'Components',
    subtitle: '气泡确认框',
    type: 'Feedback',
    title: 'Popconfirm',
    tag: 'fa-popconfirm',
  },
  popover: {
    category: 'Components',
    subtitle: '气泡卡片',
    type: 'Data Display',
    title: 'Popover',
    tag: 'fa-popover',
  },
  radio: {
    category: 'Components',
    subtitle: '单选框',
    type: 'Data Entry',
    title: 'Radio',
    tag: 'fa-radio',
  },
  rate: {
    category: 'Components',
    subtitle: '评分',
    type: 'Data Entry',
    title: 'Rate',
    tag: 'fa-rate',
    cols: 1,
  },
  tabs: {
    category: 'Components',
    subtitle: '标签页',
    type: 'Data Display',
    title: 'Tabs',
    tag: 'fa-tabs',
    cols: 1,
  },
  tag: {
    category: 'Components',
    subtitle: '标签',
    type: 'Data Display',
    title: 'Tag',
    tag: 'fa-tag',
  },
  tooltip: {
    category: 'Components',
    subtitle: '文字提示',
    type: 'Data Display',
    title: 'Tooltip',
    tag: 'fa-tooltip',
  },
  dropdown: {
    category: 'Components',
    subtitle: '下拉菜单',
    type: 'Navigation',
    title: 'Dropdown',
    tag: 'fa-dropdown',
  },
  divider: {
    category: 'Components',
    subtitle: '分割线',
    type: 'Other',
    title: 'Divider',
    tag: 'fa-divider',
  },
  collapse: {
    category: 'Components',
    subtitle: '折叠面板',
    type: 'Data Display',
    title: 'Collapse',
    tag: 'fa-collapse',
    cols: 1,
  },
  notification: {
    category: 'Components',
    subtitle: '通知提醒框',
    type: 'Feedback',
    title: 'Notification',
    tag: 'fa-notification',
  },
  message: {
    category: 'Components',
    subtitle: '全局提示',
    type: 'Feedback',
    title: 'Message',
    tag: 'fa-message',
  },
  spin: {
    category: 'Components',
    subtitle: '加载中',
    type: 'Feedback',
    title: 'Spin',
    tag: 'fa-spin',
  },
  switch: {
    category: 'Components',
    subtitle: '开关',
    type: 'Data Entry',
    title: 'Switch',
    tag: 'fa-switch',
  },
  "auto-complete": {
    category: 'Components',
    subtitle: '自动完成',
    type: 'Data Entry',
    title: 'AutoComplete',
    tag: 'fa-auto-complete',
    cols: 2,
  },
  affix: {
    category: 'Components',
    subtitle: '固钉',
    type: 'Navigation',
    title: 'Affix',
    tag: 'fa-affix',
  },
  cascader: {
    category: 'Components',
    subtitle: '级联选择',
    type: 'Data Entry',
    title: 'Cascader',
    tag: 'fa-cascader',
  },
  "back-top": {
    category: 'Components',
    subtitle: '回到顶部',
    type: 'Other',
    title: 'BackTop',
    tag: 'fa-back-top',
  },
  modal: {
    category: 'Components',
    subtitle: '对话框',
    type: 'Feedback',
    title: 'Modal',
    tag: 'fa-modal',
  },
  alert: {
    category: 'Components',
    subtitle: '警告提示',
    type: 'Feedback',
    title: 'Alert',
    tag: 'fa-alert',
  },
  "time-picker": {
    category: 'Components',
    subtitle: '时间选择框',
    type: 'Data Entry',
    title: 'TimePicker',
    tag: 'fa-time-picker',
  },
  steps: {
    category: 'Components',
    subtitle: '步骤条',
    type: 'Navigation',
    title: 'Steps',
    tag: 'fa-steps',
    cols: 1,
  },
  calendar: {
    category: 'Components',
    subtitle: '日历',
    type: 'Data Display',
    title: 'Calendar',
    tag: 'fa-calendar',
    cols: 1,
  },
  "date-picker": {
    category: 'Components',
    subtitle: '日期选择框',
    type: 'Data Entry',
    title: 'DatePicker',
    tag: 'fa-date-picker',
  },
  "locale-provider": {
    category: 'Components',
    subtitle: '国际化',
    type: 'Other',
    title: 'LocaleProvider',
    tag: 'fa-locale-provider',
    cols: 1,
  },
  slider: {
    category: 'Components',
    subtitle: '滑动输入条',
    type: 'Data Entry',
    title: 'Slider',
    tag: 'fa-slider',
  },
  progress: {
    category: 'Components',
    subtitle: '进度条',
    type: 'Feedback',
    title: 'Progress',
    tag: 'fa-progress',
  },
  timeline: {
    category: 'Components',
    subtitle: '时间轴',
    type: 'Data Display',
    title: 'Timeline',
    tag: 'fa-time-line',
  },
  table: {
    category: 'Components',
    subtitle: '表格',
    type: 'Data Display',
    title: 'Table',
    tag: 'fa-table',
    cols: 1,
  },
  "input-number": {
    category: 'Components',
    subtitle: '数字输入框',
    type: 'Data Entry',
    title: 'InputNumber',
    tag: 'fa-input-number',
  },
  transfer: {
    category: 'Components',
    subtitle: '穿梭框',
    type: 'Data Entry',
    title: 'Transfer',
    tag: 'fa-transfer',
    cols: '1',
  },
  upload: {
    category: 'Components',
    subtitle: '上传',
    type: 'Data Entry',
    title: 'Upload',
    tag: 'fa-upload',
  },
  carousel: {
    category: 'Components',
    type: 'Data Display',
    title: 'Carousel',
    subtitle: '走马灯',
    tag: 'fa-carousel',
  },
  tree: {
    category: 'Components',
    subtitle: '树形控件',
    type: 'Data Display',
    title: 'Tree',
    tag: 'fa-tree',
  },
  "tree-select": {
    category: 'Components',
    subtitle: '树选择',
    type: 'Data Entry',
    title: 'TreeSelect',
    tag: 'fa-tree-select',
  },
  layout: {
    category: 'Components',
    subtitle: '布局',
    type: 'Layout',
    title: 'Layout',
    tag: 'fa-layout',
    cols: 1,
  },
  form: {
    category: 'Components',
    subtitle: '表单',
    type: 'Data Entry',
    title: 'Form',
    tag: 'fa-form',
    cols: 1,
  },
  anchor: {
    category: 'Components',
    subtitle: '锚点',
    type: 'Other',
    title: 'Anchor',
    tag: 'fa-anchor',
    cols: 2,
  },
  list: {
    category: 'Components',
    subtitle: '列表',
    type: 'Data Display',
    title: 'List',
    tag: 'fa-list',
    cols: 1,
  },
  drawer: {
    category: 'Components',
    type: 'Feedback',
    title: 'Drawer',
    tag: 'fa-drawer',
    subtitle: '抽屉',
  },
  skeleton: {
    category: 'Components',
    type: 'Feedback',
    title: 'Skeleton',
    tag: 'fa-skeleton',
    subtitle: '骨架屏',
  },
  "config-provider": {
    category: 'Components',
    type: 'Other',
    title: 'ConfigProvider',
    tag: 'fa-config-provider',
    subtitle: '全局化配置',
  },
  comment: {
    category: 'Components',
    type: 'Data Display',
    title: 'Comment',
    tag: 'fa-comment',
    subtitle: '评论',
  },
}
